#!/usr/bin/env bash

NAME="{{environment-name}}"

if [[ -x /opt/homebrew/bin/brew ]]; then
	eval "$(/opt/homebrew/bin/brew shellenv)"
elif [[ -x /usr/local/bin/brew ]]; then
	eval "$(/usr/local/bin/brew shellenv)"
else
	echo "It doesn't look like you're using Homebrew. Good luck!"
fi

$HOME/.local/bin/"${NAME}.sh" launcher
